backend:
  name: github
  repo: antonindenis/antonindenis
  branch: main
  base_url: https://antonindenis.antonindenis.workers.dev
  auth_endpoint: /api/auth

site_url: https://antonindenis.antonindenis.workers.dev
display_url: https://antonindenis.antonindenis.workers.dev
